Repository cert-manager/makefile-modules, pull requests merged in 2024-08, with the labels that each got.

#179 Tools Module: require "bash" as we use bash in the main Makefile
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#171 Update kind.mk
  modules/kind/kind.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#181 fix: gci write should skip generated/vendor
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#182 Upgrade tools and cert-manager images
  modules/cert-manager/00_mod.mk
  modules/kind/00_kind_image_versions.mk
  modules/tools/00_mod.mk
  scripts/learn_kind_images.helper.mk
  scripts/learn_kind_images.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#183 chore: remove deprecated execinquery linter
  modules/go/.golangci.override.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#184 Add variable to configure the Helm chart app version
  modules/helm/helm.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#185 Limit self-upgrade to cert-manager org
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#186 Spelling
  Makefile
  modules/generate-verify/02_mod.mk
  modules/oci-publish/00_mod.mk
  modules/olm-bundle/00_mod.mk
  modules/repository-base/base/Makefile
  modules/tools/00_mod.mk
  scripts/learn_kind_images.helper.mk
  scripts/learn_tools_shas.helper.mk
  scripts/upgrade_base_images.sh
Labels: dco-signoff: yes, size/S, lgtm, approved
