Repository cert-manager/makefile-modules, pull requests merged in 2024-05, with the labels that each got.

#132 Fix find invocations on macOS
  modules/go/01_mod.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#131 Modify makefiles to speedup execution
  modules/repository-base/base/Makefile
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/L

#100 Upgrade all tools and images
  modules/kind/00_mod.mk
  modules/oci-build/00_mod.mk
  modules/oci-image/01_mod.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/L

#134 Fix learn shas script
  scripts/images_learn_sha.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#135 Bump cert-manager to latest v1.14.5 release
  modules/cert-manager/00_mod.mk
Labels: dco-signoff: yes, size/S

#133 Fix possible issues with maybe-push
  modules/oci-publish/01_mod.mk
  modules/oci-publish/image-exists.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#136 Remove the oci-image module, which has been replaced with oci-build and oci-publish
  modules/oci-image/01_mod.mk
  modules/oci-image/image_tool/go.mod
  modules/oci-image/image_tool/go.sum
  modules/oci-image/image_tool/main.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#139 Fix remaining issue in append-layers command
  modules/oci-build/image_tool/append_layers.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#141 Fix remaining issue in append-layers command (bis)
  modules/oci-build/image_tool/append_layers.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#143 fix 'make tools-learn-sha' on macOS
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#145 Bump kind to v0.23.0
  modules/kind/00_mod.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#151 Update kubebuilder shasums due to upstream update
  Makefile
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved
