Repository cert-manager/makefile-modules, pull requests merged in 2024-06, with the labels that each got.

#156 Bump base images to match latest-20240603 tag
  modules/oci-build/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#158 Bump helm-tool to v0.5.1
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#153 Use cert-manager v1.15.0 release
  modules/cert-manager/00_mod.mk
  scripts/images_learn_sha.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#160 Add `go-tidy` and `go-workspace` Makefile targets
  modules/go/01_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M
