Repository cert-manager/makefile-modules, pull requests merged in 2024-03, with the labels that each got.

#82 Bump helm-tool to v0.4.2
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#83 typo: strip instead of trim
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#84 regex on darwin: replace \s with [[:space:]]
  modules/help/help.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#86 Don't error in case $(...) target is not found
  modules/help/help.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#87 Bump image tool deps
  modules/oci-image/image_tool/go.mod
  modules/oci-image/image_tool/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/M

#88 Run 'go mod tidy'
  modules/oci-image/image_tool/go.mod
  modules/oci-image/image_tool/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/L

#89 Bump transitive go dependencies of image-tool
  modules/oci-image/image_tool/go.mod
  modules/oci-image/image_tool/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/L

#90 Add a make verify-govulncheck target
  README.md
  modules/go/01_mod.mk
  modules/go/README.md
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#94 Upgrade cert-manager to v1.14.4 and start using cert-manager-startupapicheck instead of cert-manager-ctl
  Makefile
  modules/cert-manager/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#95 Add golangci-lint linting
  modules/go/.golangci.override.yaml
  modules/go/01_mod.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved

#96 Add govulncheck CI job to repo root
  modules/go/01_mod.mk
  modules/go/base/.github/workflows/govulncheck.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M
