Repository cert-manager/makefile-modules, pull requests merged in 2024-01, with the labels that each got.

#12 Upgrade golang.org/x/crypto to v0.17.0
  modules/oci-image/image_tool/go.mod
  modules/oci-image/image_tool/go.sum
Labels: dco-signoff: yes, size/XS, lgtm, approved

#11 Bump klone version
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#13 Upgrade the distroless base image to the debian12 variant
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#14 Set default value for the artifacts directory
  modules/repository-base/base/Makefile
Labels: dco-signoff: yes, size/S, lgtm, approved

#15 Extract go[...].tar.gz outside of _bin/downloaded
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#17 Include version in the cert-manager yaml file name
  modules/cert-manager/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#16 Add csi-driver base image flavor
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#18 Add images-learn-sha target and improve sha tools
  Makefile
  modules/cert-manager/00_mod.mk
  modules/kind/00_mod.mk
  modules/kind/kind-image-preload.mk
  modules/tools/00_mod.mk
  scripts/images_learn_sha.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#21 Fix bug in help regex
  modules/help/help.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#24 Add an autobumper for the vendored Go version
  .github/workflows/go-auto-upgrade.yaml
  scripts/patch_go_version.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#25 Fix indentation in GH action
  .github/workflows/go-auto-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#26 Fix autobumper script to use gnused
  scripts/patch_go_version.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#28 Add goreleaser and syft as tools
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#29 Fix bug in 'make help' grep (second try)
  modules/help/help.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#30 Helm "artifacthub.io/prerelease" annotation
  modules/helm/helm.mk
  modules/repository-base/base/Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#31 Set empty 'shared_generate_targets' and 'shared_verify_targets_dirty' variables in the generate-verify module
  modules/controller-gen/01_mod.mk
  modules/generate-verify/00_mod.mk
  modules/helm/crds.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#33 BUGFIX: self-upgrade should also commit new files
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#19 Upgrade the cert-manager from v1.12.3 to v1.13.3
  modules/cert-manager/00_mod.mk
  scripts/images_learn_sha.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#34 Small tweaks to the oci-images module
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#20 Upgrade kind k8s to v1.29.0
  modules/kind/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#36 Rename 'kind_version' to 'kind_k8s_version'
  modules/kind/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#35 Refactor codegen tools and add 'defaulter-gen' and 'conversion-gen'
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#37 Update SHELLFLAGS and add comment that explains where these values come from
  Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#38 Remove extra_*_targets variables
  modules/generate-verify/00_mod.mk
  modules/generate-verify/02_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#41 Add LICENSE to repo base
  modules/repository-base/base/LICENSE
Labels: dco-signoff: yes, lgtm, approved, size/L

#40 Add OWNERS_ALIASES to repository-base module
  modules/repository-base/base/OWNERS_ALIASES
Labels: dco-signoff: yes, size/S, lgtm, approved

#32 Split oci-image module into 'executable' and 'oci-image' modules
  modules/executable/01_mod.mk
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/L

#42 Add linux/arm64 support
  modules/repository-base/base/Makefile
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#43 Add ability to configure GOEXPERIMENT for builds
  modules/executable/01_mod.mk
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#46 Tweak checkhash script
  modules/tools/util/checkhash.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#47 Fix ko/ go weirdness
  modules/executable/01_mod.mk
  modules/oci-image/01_mod.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#48 Add missing YQ tool dependency
  modules/executable/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#49 Add cosign executable
  modules/executable/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#50 Make oci_platforms conditional
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#52 Change default goreleaser arch, os combos
  modules/executable/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#53 FIX: ko was using the wrong cache directory
  modules/oci-image/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#56 Fix loading kind images on macOS
  modules/oci-image/image_tool/main.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#58 Revert deferred dependency expansion for generate to unbreak self-upgrades
  modules/generate-verify/02_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#44 Bump versions of all tools
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#60 Update kubebuilder sha values (upstream was updated)
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#61 Update kubebuilder sha values (upstream was updated) (2)
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#62 Update helm-tool: artifacthub docs
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved
