Repository cert-manager/makefile-modules, pull requests merged in 2024-07, with the labels that each got.

#165 Fix broken go upgrade script
  .github/workflows/go-auto-upgrade.yaml
  Makefile
  modules/tools/00_mod.mk
  scripts/images_learn_sha.sh
  scripts/learn_image_shas.helper.mk
  scripts/learn_image_shas.sh
  scripts/learn_tools_shas.helper.mk
  scripts/learn_tools_shas.sh
  scripts/patch_go_version.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#166 Add base image upgrade script
  .github/workflows/base-images-upgrade.yaml
  Makefile
  scripts/upgrade_base_images.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#167 Add kind upgrade script
  .github/workflows/kind-images-upgrade.yaml
  Makefile
  modules/kind/00_kind_image_versions.mk
  modules/kind/00_mod.mk
  modules/kind/kind-image-preload.mk
  scripts/learn_kind_images.helper.mk
  scripts/learn_kind_images.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#169 Only require "go" or "docker" when NEEDS_GO or NEEDS_CTR is a dependency.
  modules/kind/kind.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#162 Update GH actions using stepsecurity tool
  .github/workflows/base-images-upgrade.yaml
  .github/workflows/go-auto-upgrade.yaml
  .github/workflows/kind-images-upgrade.yaml
  modules/go/base/.github/workflows/govulncheck.yaml
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#164 Add bootstrap script and e2e tests
  .github/workflows/e2e-test.yaml
  Makefile
  bootstrap.sh
  modules/help/help.sh
  modules/kind/00_kind_image_versions.mk
  scripts/learn_kind_images.sh
  tests/e2e-projects/test-project/.golangci.yaml
  tests/e2e-projects/test-project/go.mod
  tests/e2e-projects/test-project/main.go
  tests/e2e-projects/test-project/make/00_mod.mk
  tests/e2e-projects/test-project/test-config.sh
  tests/test_e2e.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#163 Add labels to self-upgrade PR
  .github/workflows/base-images-upgrade.yaml
  .github/workflows/go-auto-upgrade.yaml
  .github/workflows/kind-images-upgrade.yaml
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#170 Update some lincenses / fix some trailing whitespace
  Makefile
  modules/kind/00_kind_image_versions.mk
  modules/licenses/00_mod.mk
  modules/olm-bundle/00_mod.mk
  modules/olm-bundle/01_mod.mk
  modules/olm-bundle/olm-to-oci/main.go
  scripts/learn_kind_images.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#172 Add dependabot update targets for the modules defined in the modules
  .github/dependabot.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#174 Restrict the github-actions glob match
  .github/dependabot.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved
