Repository cert-manager/makefile-modules, pull requests merged in 2024-04, with the labels that each got.

#99 Remove unuseful linters and increase golangci-lint timeout
  modules/go/.golangci.override.yaml
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#109 Replace tab with spaces in license header
  modules/oci-build/image_tool/append_layers.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#110 Update self-upgrade script to work on target branches other than 'main'.
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#112 Run dependabot daily instead of weekly
  modules/repository-base/base/.github/dependabot.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#113 repository-base module: improve GH configurations
  modules/repository-base/01_mod.mk
  modules/repository-base/base-dependabot/.github/dependabot.yaml
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#121 Small bug fixes and improvements
  modules/generate-verify/util/verify.sh
  modules/help/help.sh
  modules/repository-base/base/Makefile
  modules/tools/00_mod.mk
  modules/tools/util/checkhash.sh
  modules/tools/util/hash.sh
  modules/tools/util/lock.sh
  scripts/patch_go_version.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#123 Add missing Copyright header to oci-publish Makefile
  modules/oci-publish/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#124 Use ln instead of cp to fix issues with concurrent tool setup
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#125 Bump cmrel version to latest commit
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#129 Disable gomoddirectives and gomodguard linters
  modules/go/.golangci.override.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved
