Repository cert-manager/makefile-modules, pull requests merged in 2025-08, with the labels that each got.

#313 Upgrade vault
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#315 Add GOPRIVATE option for govulncheck
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#322 Manually upgrade dependencies in go.mod files
  modules/olm-bundle/olm-to-oci/go.mod
  modules/olm-bundle/olm-to-oci/go.sum
  tests/e2e-projects/test-project/go.mod
Labels: dco-signoff: yes, lgtm, approved, size/M

#324 Set PS1="" to prevent "/etc/bash.bashrc: line 7: PS1: unbound variable\n/etc/bash.bashrc" warning
  Makefile
  modules/repository-base/base/Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#326 Rename Dependabot groups
  .github/dependabot.yaml
  modules/repository-base/base-dependabot/.github/dependabot.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#312 Simplify GCI golangci-lint config with localmodule
  modules/go/.golangci.override.yaml
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#328 Revert "Simplify GCI golangci-lint config with localmodule"
  modules/go/.golangci.override.yaml
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#329 Move LICENSE file to boilerplate module
  modules/boilerplate/01_mod.mk
  modules/boilerplate/base/LICENSE
Labels: dco-signoff: yes, size/S, lgtm, approved

#331 Simplify repo base generation
  modules/go/01_mod.mk
  modules/go/base/.github/workflows/govulncheck.yaml
  modules/helm/helm.mk
  modules/repository-base/01_mod.mk
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#332 Upgrade go-licenses to be compatible with go 1.25
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#333 BUGFIX: make base dir variable names unique, fixing name collision bug
  modules/boilerplate/01_mod.mk
  modules/go/01_mod.mk
  modules/repository-base/01_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#335 Replace Dependabot Go dependency upgrades with Renovate Bot
  modules/repository-base/01_mod.mk
  modules/repository-base/base-dependabot/.github/dependabot.yaml
  modules/repository-base/base-dependabot/.github/renovate.json5
  modules/repository-base/base-dependabot/.github/workflows/renovate.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L

#336 Set Renovate ignorePaths
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#352 ci(renovate): add 'make vendor-go' to post upgrade tasks
  .github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#357 Disable Dependabot gh-action downstream upgrades
  .github/dependabot.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#363 Add ok-to-test label to downstream Renovate PRs
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#366 Add vendor-go target to Renovate postUpgradeTasks
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#370 Anchor Octo STS subject patterns
  modules/repository-base/base/.github/chainguard/make-self-upgrade.sts.yaml
  modules/repository-base/base/.github/chainguard/renovate.sts.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#368 Grant make-self-upgrade write access to workflows
  modules/repository-base/base/.github/chainguard/make-self-upgrade.sts.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#369 Remove Renovate push trigger
  modules/repository-base/base-dependabot/.github/workflows/renovate.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#383 Set cert-manager-bot as Git author of Renovate PRs
  .github/renovate.json5
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved
