Repository cert-manager/makefile-modules, pull requests merged in 2025-01, with the labels that each got.

#223 Add script to upgrade Makefile modules without the self-upgrade GH Action
  .gitignore
  upgrade_all_repos.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#230 Test downloading kind, kubectl, etcd and go
  tests/e2e-projects/test-project/test-config.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#232 Speedup learn-tools-shas script
  Makefile
  modules/tools/00_mod.mk
  scripts/learn_tools_shas.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#239 Remove use of '-T' in cp (not supported on macOS)
  modules/helm/crds.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#242 Fixing helm module CRD gen
  modules/helm/crds.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#243 Stop trying to rm CRDs dir
  modules/helm/crds.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#241 Rename and add go build options and make them work for both oci-build and executable modules
  modules/executable/00_mod.mk
  modules/executable/01_mod.mk
  modules/licenses/00_mod.mk
  modules/oci-build/00_mod.mk
  modules/oci-build/01_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/L

#244 Make the generate-govulncheck base dir configurable
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#245 Bump openshift preflight to latest
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#247 Make golangci-lint timeout configurable and increase the default to 10m
  modules/go/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#246 Add ko --image-annotation and --image-label options
  modules/oci-build/00_mod.mk
  modules/oci-build/01_mod.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved
