Repository cert-manager/makefile-modules, pull requests merged in 2025-02, with the labels that each got.

#248 Bump cert-manager to v1.17.0
  modules/cert-manager/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#249 Save the Helm chart digest to a file and use it to tag the non-v-prefixed Helm chart image
  modules/helm/helm.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#253 Spelling
  modules/go/01_mod.mk
  modules/olm-bundle/00_mod.mk
  modules/tools/util/lock.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#255 Upgrade klone to v0.1.1
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved, do-not-merge/hold

#256 Upgrade klone to v0.2.0
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#258 Bump version of preflight
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved
