Repository cert-manager/makefile-modules, pull requests merged in 2025-04, with the labels that each got.

#267 Make adding annotations and labels easier
  modules/oci-build/00_mod.mk
  modules/oci-build/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#266 Bump golang to 1.24
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#238 Upgrade tools
  modules/kind/00_kind_image_versions.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/L

#227 Pull preloaded images based on digest, not tag
  modules/kind/kind-image-preload.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#269 Change copy logic to fix macOS issues caused by 15.4
  modules/generate-verify/util/verify.sh
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#271 Use github.com/cert-manager/image-tool instead of in-tree go script
  modules/kind/kind-image-preload.mk
  modules/oci-build/01_mod.mk
  modules/oci-build/image_tool/append_layers.go
  modules/oci-build/image_tool/convert_to_docker_tar.go
  modules/oci-build/image_tool/go.mod
  modules/oci-build/image_tool/go.sum
  modules/oci-build/image_tool/list_digests.go
  modules/oci-build/image_tool/main.go
  modules/tools/00_mod.mk
  upgrade_all_repos.sh
Labels: dco-signoff: yes, lgtm, approved, size/XL

#272 BUGFIX: don't copy the '.' folder
  modules/generate-verify/util/verify.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#273 Upgrade golangci-lint to v2.1.2 fixing bugs in protogetter linter
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#276 Limit govulncheck to cert-manager org
  modules/go/base/.github/workflows/govulncheck.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#278 Don't make oci-layout folder path dependent on image tag
  modules/oci-build/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#279 Generate LICENSES files in git repo and copy them into image
  modules/licenses/00_mod.mk
  modules/licenses/01_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#280 Add kubeconform verification of helm charts
  modules/helm/helm.mk
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#281 Use INSTALL_OPTIONS before kubeconform and add datreeio to kubeconform sources
  modules/helm/helm.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#282 Fix typos in licenses module
  modules/licenses/01_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#285 kind image preload: simplify variables
  modules/kind/kind-image-preload.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#283 Save downloaded tools in user's home cache folder and share them across repos
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#286 Make Kubernetes version used by Kind configurable using K8S_VERSION
  modules/kind/00_mod.mk
Labels: dco-signoff: yes, size/S, lgtm, approved

#284 Licenses: support local licenses, add LICENSES to repo root and use local LICENSE file
  modules/licenses/01_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#287 Revert "introduce IMAGE_ARCH"
  modules/kind/kind-image-preload.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#288 Use $(ARTIFACTS) in kind-logs target
  modules/kind/kind.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved
