Repository cert-manager/makefile-modules, pull requests merged in 2025-09, with the labels that each got.

#343 ci(renovate): configure K8s patches to auto-merge
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, lgtm, approved, size/M

#390 Fix gotestsum Renovate config
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#389 Fix misbehaving Renovate Git author settings
  .github/renovate.json5
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#391 General Renovate config improvements
  .github/renovate.json5
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, lgtm, approved, size/M

#393 ci(renovate): fix dependencyDashboardApproval for major/digest
  modules/repository-base/base-dependabot/.github/renovate.json5
Labels: dco-signoff: yes, size/S, lgtm, approved

#404 Cleanup Dependabot leftovers
  modules/repository-base/01_mod.mk
  modules/repository-base/base/.github/renovate.json5
  modules/repository-base/base/.github/workflows/renovate.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#405 Add additional labels to self-upgrade PRs
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#406 Disable Renovate for github.com/inteon/go-licenses dependency
  .github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#408 Configure Renovate to rebase stale PRs
  .github/renovate.json5
  modules/repository-base/base/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#409 Use Renovate to suggest Go upgrades
  .github/workflows/go-auto-upgrade.yaml
  Makefile
  modules/tools/00_mod.mk
  scripts/patch_go_version.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#411 Add version to octo-sts/action
  .github/workflows/renovate.yaml
  modules/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#414 Correct typo group->groupName in Golang group
  .github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#416 Set Renovate gitIgnoredAuthors to fix "modified by someone else"
  .github/renovate.json5
  modules/repository-base/base/.github/renovate.json5
Labels: dco-signoff: yes, size/XS, lgtm, approved

#418 feat(tools): adding envtest support for customManagers
  .github/renovate.json5
Labels: dco-signoff: yes, size/S, lgtm, approved, tide/merge-method-squash

#422 Make the local Renovate config extend shared preset
  .github/renovate.json5
Labels: dco-signoff: yes, lgtm, approved, size/M

#431 Fix protoc version notifier
  modules/tools/00_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved
